# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport
import time


class kb_stringtie(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login',
            service_ver='release',
            async_job_check_time_ms=100, async_job_check_time_scale_percent=150, 
            async_job_check_max_time_ms=300000):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            async_job_check_time_ms=async_job_check_time_ms,
            async_job_check_time_scale_percent=async_job_check_time_scale_percent,
            async_job_check_max_time_ms=async_job_check_max_time_ms)

    def _check_job(self, job_id):
        return self._client._check_job('kb_stringtie', job_id)

    def _run_stringtie_app_submit(self, params, context=None):
        return self._client._submit_job(
             'kb_stringtie.run_stringtie_app', [params],
             self._service_ver, context)

    def run_stringtie_app(self, params, context=None):
        """
        run_stringtie_app: run StringTie app
        ref: http://ccb.jhu.edu/software/stringtie/index.shtml?t=manual
        :param params: instance of type "StringTieInput" (required params:
           alignment_object_ref: Alignment or AlignmentSet object reference
           workspace_name: the name of the workspace it gets saved to
           optional params: num_threads: number of processing threads
           junction_base: junctions that don't have spliced reads
           junction_coverage: junction coverage disable_trimming: disables
           trimming at the ends of the assembled transcripts
           min_locus_gap_sep_value: minimum locus gap separation value
           ballgown_mode: enables the output of Ballgown input table files
           skip_reads_with_no_ref: reads with no reference will be skipped
           maximum_fraction: maximum fraction of muliple-location-mapped
           reads label: prefix for the name of the output transcripts
           min_length: minimum length allowed for the predicted transcripts
           min_read_coverage: minimum input transcript coverage
           min_isoform_abundance: minimum isoform abundance merge: set
           transcript merge mode ref:
           http://ccb.jhu.edu/software/stringtie/index.shtml?t=manual) ->
           structure: parameter "alignment_object_ref" of type "obj_ref" (An
           X/Y/Z style reference), parameter "workspace_name" of String,
           parameter "merge" of type "boolean" (A boolean - 0 for false, 1
           for true. @range (0, 1)), parameter "num_threads" of Long,
           parameter "junction_base" of Long, parameter "junction_coverage"
           of Double, parameter "disable_trimming" of type "boolean" (A
           boolean - 0 for false, 1 for true. @range (0, 1)), parameter
           "min_locus_gap_sep_value" of Long, parameter "ballgown_mode" of
           type "boolean" (A boolean - 0 for false, 1 for true. @range (0,
           1)), parameter "skip_reads_with_no_ref" of type "boolean" (A
           boolean - 0 for false, 1 for true. @range (0, 1)), parameter
           "maximum_fraction" of Double, parameter "label" of String,
           parameter "min_length" of Long, parameter "min_read_coverage" of
           Double, parameter "min_isoform_abundance" of Double
        :returns: instance of type "StringTieResult" (result_directory:
           folder path that holds all files generated by run_stringtie
           expression_obj_ref: generated Expression/ExpressionSet object
           reference report_name: report name generated by KBaseReport
           report_ref: report reference generated by KBaseReport) ->
           structure: parameter "result_directory" of String, parameter
           "expression_obj_ref" of type "obj_ref" (An X/Y/Z style reference),
           parameter "report_name" of String, parameter "report_ref" of String
        """
        job_id = self._run_stringtie_app_submit(params, context)
        async_job_check_time = self._client.async_job_check_time
        while True:
            time.sleep(async_job_check_time)
            async_job_check_time = (async_job_check_time *
                self._client.async_job_check_time_scale_percent / 100.0)
            if async_job_check_time > self._client.async_job_check_max_time:
                async_job_check_time = self._client.async_job_check_max_time
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]

    def status(self, context=None):
        job_id = self._client._submit_job('kb_stringtie.status', 
            [], self._service_ver, context)
        async_job_check_time = self._client.async_job_check_time
        while True:
            time.sleep(async_job_check_time)
            async_job_check_time = (async_job_check_time *
                self._client.async_job_check_time_scale_percent / 100.0)
            if async_job_check_time > self._client.async_job_check_max_time:
                async_job_check_time = self._client.async_job_check_max_time
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]
