# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class STAR(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def run_star(self, params, context=None):
        """
        :param params: instance of type "AlignReadsParams" (Will align the
           input reads (or set of reads specified in a SampleSet) to the
           specified assembly or assembly for the specified Genome (accepts
           Assembly, ContigSet, or Genome types) and produces a
           ReadsAlignment object, or in the case of a SampleSet, a
           ReadsAlignmentSet object obj_ref genome_ref: KBase workspace
           reference Genome obj_ref readsset_ref: the workspace reference for
           the set of reads to align, referring to either a
           SingleEnd/PairedEnd reads, or a ReadsSet input string
           output_workspace - name or id of the WS to save the results to,
           provided by the narrative for housing output in KBase string
           output_name - name of the output ReadsAlignment or
           ReadsAlignmentSet object int runThreadN - the number of threads
           for STAR to use (default to 2) string outFileNamePrefix: you can
           change the file prefixes using --outFileNamePrefix
           /path/to/output/dir/prefix By default, this parameter is ./, i.e.
           all output files are written in current directory without a prefix
           string quantMode: types of quantification
           requested--none/TranscriptomeSAM/GeneCounts int
           outFilterMultimapNmax: max number of multiple alignments allowed
           for a read: if exceeded, the read is considered unmapped, default
           to 20 int alignSJoverhangMin: minimum overhang for unannotated
           junctions, default to 8 int alignSJDBoverhangMin: minimum overhang
           for annotated junctions, default to 1 int outFilterMismatchNmax:
           maximum number of mismatches per pair, large number switches off
           this filter, default to 999 int alignIntronMin: minimum intron
           length, default to 20 int alignIntronMax: maximum intron length,
           default to 1000000 int alignMatesGapMax: maximum genomic distance
           between mates, default to 1000000 int create_report: = 1 if we
           build a report, 0 otherwise. (default 1) (shouldn not be user set
           - mainly used for subtasks) @optional alignmentset_suffix
           @optional alignIntronMin @optional alignIntronMax @optional
           alignMatesGapMax @optional alignSJoverhangMin @optional
           alignSJDBoverhangMin @optional quantMode @optional outFilterType
           @optional outFilterMultimapNmax @optional outSAMtype @optional
           outSAMattrIHstart @optional outSAMstrandField @optional
           outFilterMismatchNmax @optional outFileNamePrefix @optional
           runThreadN) -> structure: parameter "readsset_ref" of type
           "obj_ref" (An X/Y/Z style reference), parameter "genome_ref" of
           type "obj_ref" (An X/Y/Z style reference), parameter
           "output_workspace" of String, parameter "output_name" of String,
           parameter "alignment_suffix" of String, parameter "condition" of
           String, parameter "concurrent_njsw_tasks" of Long, parameter
           "concurrent_local_tasks" of Long, parameter "outSAMunmapped" of
           String, parameter "create_report" of type "bool" (A boolean - 0
           for false, 1 for true. @range (0, 1)), parameter
           "alignmentset_suffix" of String, parameter "alignIntronMin" of
           Long, parameter "alignIntronMax" of Long, parameter
           "alignMatesGapMax" of Long, parameter "alignSJoverhangMin" of
           Long, parameter "alignSJDBoverhangMin" of Long, parameter
           "quantMode" of String, parameter "outFilterType" of String,
           parameter "outFilterMultimapNmax" of Long, parameter "outSAMtype"
           of String, parameter "outSAMattrIHstart" of Long, parameter
           "outSAMstrandField" of String, parameter "outFilterMismatchNmax"
           of Long, parameter "outFileNamePrefix" of String, parameter
           "runThreadN" of Long
        :returns: instance of type "AlignReadsResult" (Here is the definition
           of the output of the function.  The output can be used by other
           SDK modules which call your code, or the output visualizations in
           the Narrative.  'report_name' and 'report_ref' are special output
           fields- if defined, the Narrative can automatically render your
           Report. output_directory: folder path that holds all output files
           generated by run_star alignmentset_ref: if an alignment set is
           created alignment_objs: for each individual alignment created. The
           keys are the references to the reads object being aligned.
           report_name: report name generated by KBaseReport report_ref:
           report reference generated by KBaseReport) -> structure: parameter
           "output_directory" of String, parameter "report_name" of String,
           parameter "report_ref" of type "obj_ref" (An X/Y/Z style
           reference), parameter "alignmentset_ref" of type "obj_ref" (An
           X/Y/Z style reference), parameter "alignment_objs" of mapping from
           type "obj_ref" (An X/Y/Z style reference) to type "AlignmentObj"
           (Created alignment object returned. ref = the workspace reference
           of the new alignment object name = the name of the new object, for
           convenience.) -> structure: parameter "ref" of type "obj_ref" (An
           X/Y/Z style reference), parameter "name" of String
        """
        return self._client.call_method(
            'STAR.run_star',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('STAR.status',
                                        [], self._service_ver, context)
